from __future__ import annotations

POLICY_CHANGES = [
    {
        'id': 'chg_20260124',
        'title': 'L2 기준점 65→60 하향 검토',
        'type': 'rule_threshold',
        'version': 'v2.3.2 (draft)',
        'deployedAt': '2026-01-24T14:00:00+09:00',
        'deployedBy': '-',
        'status': 'reviewing',
        'description': '경기도 일부 센터에서 L2 누락 케이스 증가. 기준점 하향 검토 중.',
        'before': {'slaRate': 89.8, 'responseTimeliness': 85.1, 'completionRate': 92.7, 'dataFulfillment': 94.3},
        'after': {'slaRate': 89.8, 'responseTimeliness': 85.1, 'completionRate': 92.7, 'dataFulfillment': 94.3},
        'impactSummary': [
            {'kpi': 'SLA', 'label': 'SLA 준수율', 'changePp': 0, 'verdict': 'insignificant'},
            {'kpi': 'RESP', 'label': '응답 적시율', 'changePp': 0, 'verdict': 'insignificant'},
            {'kpi': 'COMP', 'label': '처리 완료율', 'changePp': 0, 'verdict': 'insignificant'},
            {'kpi': 'DATA', 'label': '데이터 충족률', 'changePp': 0, 'verdict': 'insignificant'},
        ],
        'affectedRegions': ['전국'],
        'riskLevel': 'medium',
        'requestedBy': '이영희 (서울시)',
        'approvedBy': None,
        'currentRule': '점수 ≥ 65 → L2',
        'proposedRule': '점수 ≥ 60 → L2',
        'reason': '60~64점 구간 이탈률 증가에 대한 사전 대응 검토.',
    },
    {
        'id': 'chg_20260120',
        'title': 'L2 기준점 60→65 상향 조정',
        'type': 'rule_threshold',
        'version': 'v2.3.1',
        'deployedAt': '2026-01-20T09:00:00+09:00',
        'deployedBy': '박중앙 (보건복지부)',
        'status': 'deployed',
        'description': 'L2 대상 점수 기준을 상향 조정.',
        'before': {'slaRate': 87.2, 'responseTimeliness': 82.5, 'completionRate': 91.3, 'dataFulfillment': 94.1},
        'after': {'slaRate': 89.8, 'responseTimeliness': 85.1, 'completionRate': 92.7, 'dataFulfillment': 94.3},
        'impactSummary': [
            {'kpi': 'SLA', 'label': 'SLA 준수율', 'changePp': 2.6, 'verdict': 'improved'},
            {'kpi': 'RESP', 'label': '응답 적시율', 'changePp': 2.6, 'verdict': 'improved'},
            {'kpi': 'COMP', 'label': '처리 완료율', 'changePp': 1.4, 'verdict': 'improved'},
            {'kpi': 'DATA', 'label': '데이터 충족률', 'changePp': 0.2, 'verdict': 'insignificant'},
        ],
        'affectedRegions': ['전국'],
        'riskLevel': 'medium',
        'requestedBy': '박중앙 (보건복지부)',
        'approvedBy': '김정책 (보건복지부)',
    },
    {
        'id': 'chg_20260110',
        'title': '예측 모델 v3.2 배포',
        'type': 'model_version',
        'version': 'v3.2.0',
        'deployedAt': '2026-01-10T11:00:00+09:00',
        'deployedBy': '이모델 (중앙)',
        'status': 'deployed',
        'description': '위험 예측 모델 v3.2 전국 배포.',
        'before': {'slaRate': 84.1, 'responseTimeliness': 78.9, 'completionRate': 88.2, 'dataFulfillment': 93.2},
        'after': {'slaRate': 85.8, 'responseTimeliness': 80.1, 'completionRate': 89.5, 'dataFulfillment': 93.8},
        'impactSummary': [
            {'kpi': 'SLA', 'label': 'SLA 준수율', 'changePp': 1.7, 'verdict': 'improved'},
            {'kpi': 'RESP', 'label': '응답 적시율', 'changePp': 1.2, 'verdict': 'improved'},
            {'kpi': 'COMP', 'label': '처리 완료율', 'changePp': 1.3, 'verdict': 'improved'},
            {'kpi': 'DATA', 'label': '데이터 충족률', 'changePp': 0.6, 'verdict': 'insignificant'},
        ],
        'affectedRegions': ['전국'],
        'riskLevel': 'low',
        'requestedBy': '이모델 (중앙)',
        'approvedBy': '박중앙 (보건복지부)',
    },
]

DRIVER_ANALYSIS = [
    {
        'key': 'ops_bottleneck',
        'label': '운영 병목',
        'icon': '⚙️',
        'description': '센터 인력, SLA 위반, 미처리 케이스 누적 등 운영 병목 분석',
        'severity': 'critical',
        'score': 38,
        'contributionPct': 35,
        'topRegions': [
            {'code': '26', 'name': '부산광역시', 'score': 22, 'detail': 'SLA 78.2%, 미처리 42건'},
            {'code': '27', 'name': '대구광역시', 'score': 35, 'detail': 'SLA 82.5%, 인력 부족'},
            {'code': '31', 'name': '경기도', 'score': 41, 'detail': '일부 시군 SLA 84%'},
        ],
        'indicators': [
            {'label': '평균 SLA 준수율', 'value': 89.8, 'unit': '%', 'threshold': 90, 'status': 'yellow'},
            {'label': '미처리 케이스 총수', 'value': 156, 'unit': '건', 'threshold': 100, 'status': 'red'},
            {'label': '평균 처리 소요시간', 'value': 4.2, 'unit': '일', 'threshold': 3, 'status': 'red'},
            {'label': '인력 대비 케이스 비율', 'value': 28.5, 'unit': '건/인', 'threshold': 25, 'status': 'yellow'},
        ],
    },
    {
        'key': 'data_quality',
        'label': '데이터 품질',
        'icon': '📊',
        'description': '데이터 결측, 업데이트 지연, 입력 오류 등 데이터 품질 진단',
        'severity': 'warning',
        'score': 62,
        'contributionPct': 28,
        'topRegions': [
            {'code': '26', 'name': '부산광역시', 'score': 48, 'detail': '필수필드 누락률 8.2%'},
            {'code': '27', 'name': '대구광역시', 'score': 55, 'detail': '입력 지연 평균 48시간'},
            {'code': '28', 'name': '인천광역시', 'score': 61, 'detail': '중복 케이스 12건'},
        ],
        'indicators': [
            {'label': '데이터 완전성', 'value': 95.5, 'unit': '%', 'threshold': 95, 'status': 'green'},
            {'label': '데이터 정확성', 'value': 96.8, 'unit': '%', 'threshold': 95, 'status': 'green'},
            {'label': '데이터 적시성', 'value': 93.8, 'unit': '%', 'threshold': 95, 'status': 'yellow'},
            {'label': '결측 필드 비율', 'value': 4.5, 'unit': '%', 'threshold': 5, 'status': 'yellow'},
        ],
    },
]

QUALITY_ALERTS = [
    {
        'id': 'qa_001',
        'type': 'sla_breach',
        'severity': 'critical',
        'title': '부산광역시 SLA 위반 경보',
        'description': 'SLA 준수율 78.2%로 기준(85%) 미달. 미처리 42건 누적.',
        'region': '부산광역시',
        'detectedAt': '2026-01-24T08:00:00+09:00',
        'resolved': False,
        'relatedDriver': 'ops_bottleneck',
    },
    {
        'id': 'qa_002',
        'type': 'update_delay',
        'severity': 'warning',
        'title': '대구광역시 데이터 입력 지연',
        'description': '평균 입력 지연 48시간. 기준(24시간) 초과.',
        'region': '대구광역시',
        'detectedAt': '2026-01-23T10:00:00+09:00',
        'resolved': False,
        'relatedDriver': 'data_quality',
    },
]

UNIFIED_AUDIT = [
    {
        'id': 'ua_001',
        'timestamp': '2026-01-24T09:15:00+09:00',
        'type': 'violation',
        'severity': 'high',
        'status': 'reviewing',
        'title': '권한 없는 PII 접근 시도',
        'actor': '김상담 (CS-1042)',
        'actorRole': '상담사',
        'center': '강남구 센터',
        'target': '시민 개인정보 DB',
        'violationType': '개인정보 무단 접근',
        'violatedRegulation': '개인정보보호법 제29조',
        'cause': '담당 케이스 외 시민 정보 조회 시도.',
        'relatedChangeId': None,
        'requestor': '김상담 (CS-1042)',
        'approver': None,
        'executor': '시스템 자동 차단',
        'policyRef': '개인정보보호법 제29조',
        'internalStandardId': 'SEC-003',
        'approvalComment': '접근 차단 후 센터장 통보.',
        'rationale': '비담당 케이스 PII 접근은 즉시 차단 대상.',
        'kpiSnapshot': {'slaRate': 89.8, 'riskTop3': ['서울 강남구', '서울 송파구', '서울 서초구'], 'regionContext': '서울특별시'},
    },
    {
        'id': 'ua_004',
        'timestamp': '2026-01-20T09:00:00+09:00',
        'type': 'policy_change',
        'severity': 'medium',
        'status': 'resolved',
        'title': 'L2 기준점 60→65 상향 배포',
        'actor': '박중앙',
        'actorRole': '보건복지부 중앙관리자',
        'center': None,
        'target': 'L2 분류 기준점 (전국)',
        'violationType': None,
        'violatedRegulation': None,
        'cause': '센터 업무량 최적화를 위한 조치.',
        'relatedChangeId': 'chg_20260120',
        'requestor': '박중앙 (보건복지부)',
        'approver': '김정책 (정책심의위)',
        'executor': '박중앙 (보건복지부)',
        'policyRef': '위험 분류 기준 운영지침 v4.2',
        'internalStandardId': 'RULE-L2-001',
        'approvalComment': '샌드박스 평가 통과 후 배포.',
        'rationale': '샌드박스 평가 통과.',
        'kpiSnapshot': {'slaRate': 87.2, 'riskTop3': ['부산 해운대구', '대구 달서구', '경기 안산시'], 'regionContext': '전국'},
    },
]
